name: Run scrapers

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '4,14,24,34,44,54 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '1.16.0-beta1'
    - name: Run scrapers
      run: ./bin/scrape.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: $timestamp" || exit 0
        git push
